# Generated by Django 5.1.7 on 2025-03-20 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
        ('users', '0002_alter_church_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='church',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='users.church'),
        ),
    ]
