# Generated by Django 5.1.7 on 2025-03-20 01:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='church',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='churches', to=settings.AUTH_USER_MODEL, verbose_name='Usuários'),
        ),
    ]
